name: macOS

on:
  push:
    branches: [ "*" ] # DEV: DON'T PR THIS !!!
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  osx:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-13 # x68
        - macos-14 # arm64

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies, set python environment
        run: |
          # Delete GitHub Python, See https://github.com/orgs/Homebrew/discussions/3895#discussioncomment-4130560
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -print -delete

          brew install fftw hdf5 boost-python3 numpy cfitsio wcslib gsl ninja

          # ensure we use homebrew python (needed for macos-13-x86, not macos-14-arm64)
          export PATH=$(brew --prefix python)/bin:${PATH}
          echo PATH=$PATH | tee -a $GITHUB_ENV

      - name: set up build folder with WSRT measures
        run: |
          wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar -O WSRT_Measures.ztar
          mkdir -p build
          cd build
          tar zxvf ../WSRT_Measures.ztar
          rm ../WSRT_Measures.ztar

      - name: configure
        run: |
          cd build
          cmake \
            -G Ninja \
            -DCMAKE_Fortran_COMPILER=$(which gfortran-13) \
            -DCMAKE_PREFIX_PATH=/usr/local/ \
            -DBoost_NO_BOOST_CMAKE=True \
            -DBUILD_TESTING=ON \
            -DBUILD_PYTHON=OFF \
            -DBUILD_PYTHON3=ON \
            -DPython3_EXECUTABLE=$(which python3) \
            -DUSE_HDF5=ON \
            -DUSE_OPENMP=OFF \
            -DDATA_DIR=. \
            ..

      - name: make
        run: cmake --build build

      - name: run tests
        run: |
          cd build
          CTEST_OUTPUT_ON_FAILURE=1 ctest

      - name: install
        run: cmake --build build --target install
